"""add favicon cache table with virtual_host_id FK

Revision ID: 9c921bfc56e6
Revises: f334f396e38f
Create Date: 2026-05-20 05:43:26.418945

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c921bfc56e6"
down_revision: Union[str, Sequence[str], None] = "f334f396e38f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fpm_dashboard_favicon_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("virtual_host_id", sa.Integer(), nullable=False),
        sa.Column("favicon_data_url", sa.Text(), nullable=False),
        sa.Column("is_placeholder", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["virtual_host_id"], ["ferron_virtual_host.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("virtual_host_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    raise RuntimeError("Downgrades are not supported. Restore from backup.")
