"""initial schema

Revision ID: f334f396e38f
Revises:
Create Date: 2026-01-15 16:24:27.429426

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f334f396e38f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_auth_users_username"), ["username"], unique=True)

    op.create_table(
        "ferron_global_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("default_http_port", sa.Integer(), nullable=False),
        sa.Column("default_https_port", sa.Integer(), nullable=False),
        sa.Column("is_h1_protocol_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_h2_protocol_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_h3_protocol_enabled", sa.Boolean(), nullable=False),
        sa.Column("timeout", sa.Integer(), nullable=False),
        sa.Column("cache_max_entries", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ferron_virtual_host",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("virtual_host_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("virtual_host_name"),
    )
    op.create_table(
        "auth_refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_refresh_tokens_token"), ["token"], unique=True)

    op.create_table(
        "ferron_load_balancer_config",
        sa.Column("cache", sa.Boolean(), nullable=False),
        sa.Column("cache_max_age", sa.Integer(), nullable=False),
        sa.Column("preserve_host_header", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("virtual_host_id", sa.Integer(), nullable=False),
        sa.Column("lb_health_check", sa.Boolean(), nullable=False),
        sa.Column("lb_health_check_max_fails", sa.Integer(), nullable=False),
        sa.Column("lb_health_check_window", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["virtual_host_id"], ["ferron_virtual_host.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ferron_reverse_proxy_config",
        sa.Column("cache", sa.Boolean(), nullable=False),
        sa.Column("cache_max_age", sa.Integer(), nullable=False),
        sa.Column("preserve_host_header", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("virtual_host_id", sa.Integer(), nullable=False),
        sa.Column("backend_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("use_unix_socket", sa.Boolean(), nullable=False),
        sa.Column("unix_socket_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["virtual_host_id"], ["ferron_virtual_host.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ferron_static_file_config",
        sa.Column("cache", sa.Boolean(), nullable=False),
        sa.Column("cache_max_age", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("virtual_host_id", sa.Integer(), nullable=False),
        sa.Column("static_files_dir", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("use_spa", sa.Boolean(), nullable=False),
        sa.Column("compressed", sa.Boolean(), nullable=False),
        sa.Column("directory_listing", sa.Boolean(), nullable=False),
        sa.Column("precompressed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["virtual_host_id"], ["ferron_virtual_host.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ferron_load_balancer_backend_url",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("virtual_host_id", sa.Integer(), nullable=False),
        sa.Column("used_in_load_balancer", sa.Integer(), nullable=False),
        sa.Column("backend_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["used_in_load_balancer"], ["ferron_load_balancer_config.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["virtual_host_id"], ["ferron_virtual_host.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    raise RuntimeError("Downgrades are not supported. Restore from backup.")
