DEFAULT_HTTP_PORT = 80
DEFAULT_HTTPS_PORT = 443
DEFAULT_IS_H1_PROTOCOL_ENABLED = True
DEFAULT_IS_H2_PROTOCOL_ENABLED = True
DEFAULT_IS_H3_PROTOCOL_ENABLED = False
DEFAULT_TIMEOUT = 300000
DEFAULT_CACHE_MAX_ENTRIES = 1024