# JWT Configuration
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 10
REFRESH_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7  # 7 days

USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 255
PASSWORD_MIN_LENGTH = 8
